export const PERMISSIONS = {
  ACADEMIC: {
    PROGRAM: {
      VIEW: 'ACADEMIC:PROGRAM:VIEW',
      CREATE: 'ACADEMIC:PROGRAM:CREATE',
      UPDATE: 'ACADEMIC:PROGRAM:UPDATE',
      DELETE: 'ACADEMIC:PROGRAM:DELETE',
    },
    COURSE: {
      VIEW: 'ACADEMIC:COURSE:VIEW',
      CREATE: 'ACADEMIC:COURSE:CREATE',
      UPDATE: 'ACADEMIC:COURSE:UPDATE',
      DELETE: 'ACADEMIC:COURSE:DELETE',
    },
    CLASS: {
      VIEW: 'ACADEMIC:CLASS:VIEW',
      CREATE: 'ACADEMIC:CLASS:CREATE',
      UPDATE: 'ACADEMIC:CLASS:UPDATE',
      DELETE: 'ACADEMIC:CLASS:DELETE',
    },
    LEVEL: {
      VIEW: 'ACADEMIC:LEVEL:VIEW',
      CREATE: 'ACADEMIC:LEVEL:CREATE',
      UPDATE: 'ACADEMIC:LEVEL:UPDATE',
      DELETE: 'ACADEMIC:LEVEL:DELETE',
    },
  },
  FINANCE: {
    PAYMENT: {
      VIEW: 'FINANCE:PAYMENT:VIEW',
      COLLECT: 'FINANCE:PAYMENT:COLLECT',
      REFUND: 'FINANCE:PAYMENT:REFUND',
    },
    INVOICE: {
      VIEW: 'FINANCE:INVOICE:VIEW',
      CREATE: 'FINANCE:INVOICE:CREATE',
      UPDATE: 'FINANCE:INVOICE:UPDATE',
      DELETE: 'FINANCE:INVOICE:DELETE',
    },
    FEE_TEMPLATE: {
      VIEW: 'FINANCE:FEE_TEMPLATE:VIEW',
      CREATE: 'FINANCE:FEE_TEMPLATE:CREATE',
      UPDATE: 'FINANCE:FEE_TEMPLATE:UPDATE',
      DELETE: 'FINANCE:FEE_TEMPLATE:DELETE',
    },
  },
  STUDENT: {
    PROFILE: {
      VIEW: 'STUDENT:PROFILE:VIEW',
      CREATE: 'STUDENT:PROFILE:CREATE',
      UPDATE: 'STUDENT:PROFILE:UPDATE',
      DELETE: 'STUDENT:PROFILE:DELETE',
    },
    ENROLLMENT: {
      VIEW: 'STUDENT:ENROLLMENT:VIEW',
      CREATE: 'STUDENT:ENROLLMENT:CREATE',
      UPDATE: 'STUDENT:ENROLLMENT:UPDATE',
    },
  },
  ADMIN: {
    USER: {
      VIEW: 'ADMIN:USER:VIEW',
      CREATE: 'ADMIN:USER:CREATE',
      UPDATE: 'ADMIN:USER:UPDATE',
      DELETE: 'ADMIN:USER:DELETE',
    },
    ROLE: {
      VIEW: 'ADMIN:ROLE:VIEW',
      CREATE: 'ADMIN:ROLE:CREATE',
      UPDATE: 'ADMIN:ROLE:UPDATE',
      DELETE: 'ADMIN:ROLE:DELETE',
    },
    AUDIT: {
      VIEW: 'ADMIN:AUDIT:VIEW',
    },
  },
} as const
