export const PERMISSIONS = {
  ACADEMIC: {
    PROGRAM: {
      VIEW: 'ACADEMIC:PROGRAM:VIEW',
      CREATE: 'ACADEMIC:PROGRAM:CREATE',
      UPDATE: 'ACADEMIC:PROGRAM:UPDATE',
      DELETE: 'ACADEMIC:PROGRAM:DELETE',
    },
    COURSE: {
      VIEW: 'ACADEMIC:COURSE:VIEW',
      CREATE: 'ACADEMIC:COURSE:CREATE',
      UPDATE: 'ACADEMIC:COURSE:UPDATE',
      DELETE: 'ACADEMIC:COURSE:DELETE',
    },
    CLASS: {
      VIEW: 'ACADEMIC:CLASS:VIEW',
      CREATE: 'ACADEMIC:CLASS:CREATE',
      UPDATE: 'ACADEMIC:CLASS:UPDATE',
      DELETE: 'ACADEMIC:CLASS:DELETE',
    },
    LEVEL: {
      VIEW: 'ACADEMIC:LEVEL:VIEW',
      CREATE: 'ACADEMIC:LEVEL:CREATE',
      UPDATE: 'ACADEMIC:LEVEL:UPDATE',
      DELETE: 'ACADEMIC:LEVEL:DELETE',
    },
  },
  FINANCE: {
    PAYMENT: {
      VIEW: 'FINANCE:PAYMENT:VIEW',
      COLLECT: 'FINANCE:PAYMENT:COLLECT',
      REFUND: 'FINANCE:PAYMENT:REFUND',
    },
    INVOICE: {
      VIEW: 'FINANCE:INVOICE:VIEW',
      CREATE: 'FINANCE:INVOICE:CREATE',
      UPDATE: 'FINANCE:INVOICE:UPDATE',
      DELETE: 'FINANCE:INVOICE:DELETE',
    },
    FEE_TEMPLATE: {
      VIEW: 'FINANCE:FEE_TEMPLATE:VIEW',
      CREATE: 'FINANCE:FEE_TEMPLATE:CREATE',
      UPDATE: 'FINANCE:FEE_TEMPLATE:UPDATE',
      DELETE: 'FINANCE:FEE_TEMPLATE:DELETE',
    },
  },
  STUDENT: {
    PROFILE: {
      VIEW: 'STUDENT:PROFILE:VIEW',
      CREATE: 'STUDENT:PROFILE:CREATE',
      UPDATE: 'STUDENT:PROFILE:UPDATE',
      DELETE: 'STUDENT:PROFILE:DELETE',
    },
    ENROLLMENT: {
      VIEW: 'ENROLLMENT:ENROLLMENT:VIEW',
      CREATE: 'ENROLLMENT:ENROLLMENT:CREATE',
      UPDATE: 'ENROLLMENT:ENROLLMENT:UPDATE',
    },
  },
  BILLING: {
    FEE_MAPPING: {
      VIEW: 'BILLING:PROGRAM_LEVEL_FEE_MAPPING:VIEW',
      CREATE: 'BILLING:PROGRAM_LEVEL_FEE_MAPPING:CREATE',
      UPDATE: 'BILLING:PROGRAM_LEVEL_FEE_MAPPING:UPDATE',
    },
    DISCOUNT: {
      VIEW: 'BILLING:DISCOUNT:VIEW',
      CREATE: 'BILLING:DISCOUNT:CREATE',
      UPDATE: 'BILLING:DISCOUNT:UPDATE',
      APPLY: 'BILLING:DISCOUNT:APPLY',
      REMOVE: 'BILLING:DISCOUNT:REMOVE',
    },
  },
  ADMIN: {
    USER: {
      VIEW: 'USER:USER:VIEW',
      CREATE: 'USER:USER:CREATE',
      UPDATE: 'USER:USER:UPDATE',
      DELETE: 'USER:USER:DELETE',
    },
    ROLE: {
      VIEW: 'USER:ROLE:VIEW',
      CREATE: 'USER:ROLE:CREATE',
      UPDATE: 'USER:ROLE:UPDATE',
      DELETE: 'USER:ROLE:DELETE',
    },
    AUDIT: {
      VIEW: 'USER:AUDIT:VIEW',
    },
    PERMISSION_MATRIX: {
      VIEW: 'ROLE_PERMISSION:ROLE_PERMISSION:VIEW',
      UPDATE: 'ROLE_PERMISSION:ROLE_PERMISSION:UPDATE',
    },
  },
} as const
