/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PlatformDashboardIndexRouteImport } from './routes/platform/dashboard/index'
import { Route as AppUsersAccessIndexRouteImport } from './routes/_app/users-access/index'
import { Route as AppStudentsIndexRouteImport } from './routes/_app/students/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppFinanceIndexRouteImport } from './routes/_app/finance/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppBillingIndexRouteImport } from './routes/_app/billing/index'
import { Route as AppAuditIndexRouteImport } from './routes/_app/audit/index'
import { Route as AppAcademicIndexRouteImport } from './routes/_app/academic/index'
import { Route as AppStudentsNewRouteImport } from './routes/_app/students/new'
import { Route as AppStudentsStudentIdRouteImport } from './routes/_app/students/$studentId'
import { Route as AppUsersAccessUserListIndexRouteImport } from './routes/_app/users-access/user-list/index'
import { Route as AppUsersAccessPermissionMatrixIndexRouteImport } from './routes/_app/users-access/permission-matrix/index'
import { Route as AppFeesDiscountsIndexRouteImport } from './routes/_app/fees/discounts/index'
import { Route as AppFeesCategoriesIndexRouteImport } from './routes/_app/fees/categories/index'
import { Route as AppEnrollmentIntakesIndexRouteImport } from './routes/_app/enrollment/intakes/index'
import { Route as AppEnrollmentIntakeBatchIndexRouteImport } from './routes/_app/enrollment/intake-batch/index'
import { Route as AppEnrollmentBatchesIndexRouteImport } from './routes/_app/enrollment/batches/index'
import { Route as AppEnrollmentAcademicYearsIndexRouteImport } from './routes/_app/enrollment/academic-years/index'
import { Route as AppBillingFeeMappingsIndexRouteImport } from './routes/_app/billing/fee-mappings/index'
import { Route as AppAcademicProgramsIndexRouteImport } from './routes/_app/academic/programs/index'
import { Route as AppAcademicLevelsIndexRouteImport } from './routes/_app/academic/levels/index'
import { Route as AppAcademicClassesIndexRouteImport } from './routes/_app/academic/classes/index'
import { Route as AppStudentsStudentIdVisaRouteImport } from './routes/_app/students/$studentId/visa'
import { Route as AppStudentsStudentIdProfileRouteImport } from './routes/_app/students/$studentId/profile'
import { Route as AppStudentsStudentIdFinanceRouteImport } from './routes/_app/students/$studentId/finance'
import { Route as AppStudentsStudentIdEnrollmentHistoryRouteImport } from './routes/_app/students/$studentId/enrollment-history'
import { Route as AppStudentsStudentIdEditRouteImport } from './routes/_app/students/$studentId/edit'
import { Route as AppStudentsStudentIdDocumentsRouteImport } from './routes/_app/students/$studentId/documents'
import { Route as AppStudentsStudentIdAuditRouteImport } from './routes/_app/students/$studentId/audit'

const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const PlatformDashboardIndexRoute = PlatformDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => PlatformRoute,
} as any)
const AppUsersAccessIndexRoute = AppUsersAccessIndexRouteImport.update({
  id: '/users-access/',
  path: '/users-access/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicIndexRoute = AppAcademicIndexRouteImport.update({
  id: '/academic/',
  path: '/academic/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsNewRoute = AppStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersAccessUserListIndexRoute =
  AppUsersAccessUserListIndexRouteImport.update({
    id: '/users-access/user-list/',
    path: '/users-access/user-list/',
    getParentRoute: () => AppRoute,
  } as any)
const AppUsersAccessPermissionMatrixIndexRoute =
  AppUsersAccessPermissionMatrixIndexRouteImport.update({
    id: '/users-access/permission-matrix/',
    path: '/users-access/permission-matrix/',
    getParentRoute: () => AppRoute,
  } as any)
const AppFeesDiscountsIndexRoute = AppFeesDiscountsIndexRouteImport.update({
  id: '/fees/discounts/',
  path: '/fees/discounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesCategoriesIndexRoute = AppFeesCategoriesIndexRouteImport.update({
  id: '/fees/categories/',
  path: '/fees/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppEnrollmentIntakesIndexRoute =
  AppEnrollmentIntakesIndexRouteImport.update({
    id: '/enrollment/intakes/',
    path: '/enrollment/intakes/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEnrollmentIntakeBatchIndexRoute =
  AppEnrollmentIntakeBatchIndexRouteImport.update({
    id: '/enrollment/intake-batch/',
    path: '/enrollment/intake-batch/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEnrollmentBatchesIndexRoute =
  AppEnrollmentBatchesIndexRouteImport.update({
    id: '/enrollment/batches/',
    path: '/enrollment/batches/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEnrollmentAcademicYearsIndexRoute =
  AppEnrollmentAcademicYearsIndexRouteImport.update({
    id: '/enrollment/academic-years/',
    path: '/enrollment/academic-years/',
    getParentRoute: () => AppRoute,
  } as any)
const AppBillingFeeMappingsIndexRoute =
  AppBillingFeeMappingsIndexRouteImport.update({
    id: '/billing/fee-mappings/',
    path: '/billing/fee-mappings/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAcademicProgramsIndexRoute =
  AppAcademicProgramsIndexRouteImport.update({
    id: '/academic/programs/',
    path: '/academic/programs/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAcademicLevelsIndexRoute = AppAcademicLevelsIndexRouteImport.update({
  id: '/academic/levels/',
  path: '/academic/levels/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicClassesIndexRoute = AppAcademicClassesIndexRouteImport.update({
  id: '/academic/classes/',
  path: '/academic/classes/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdVisaRoute =
  AppStudentsStudentIdVisaRouteImport.update({
    id: '/visa',
    path: '/visa',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)
const AppStudentsStudentIdProfileRoute =
  AppStudentsStudentIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)
const AppStudentsStudentIdFinanceRoute =
  AppStudentsStudentIdFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)
const AppStudentsStudentIdEnrollmentHistoryRoute =
  AppStudentsStudentIdEnrollmentHistoryRouteImport.update({
    id: '/enrollment-history',
    path: '/enrollment-history',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)
const AppStudentsStudentIdEditRoute =
  AppStudentsStudentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)
const AppStudentsStudentIdDocumentsRoute =
  AppStudentsStudentIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)
const AppStudentsStudentIdAuditRoute =
  AppStudentsStudentIdAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platform': typeof PlatformRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/students/$studentId': typeof AppStudentsStudentIdRouteWithChildren
  '/students/new': typeof AppStudentsNewRoute
  '/academic/': typeof AppAcademicIndexRoute
  '/audit/': typeof AppAuditIndexRoute
  '/billing/': typeof AppBillingIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/finance/': typeof AppFinanceIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/students/': typeof AppStudentsIndexRoute
  '/users-access/': typeof AppUsersAccessIndexRoute
  '/platform/dashboard/': typeof PlatformDashboardIndexRoute
  '/students/$studentId/audit': typeof AppStudentsStudentIdAuditRoute
  '/students/$studentId/documents': typeof AppStudentsStudentIdDocumentsRoute
  '/students/$studentId/edit': typeof AppStudentsStudentIdEditRoute
  '/students/$studentId/enrollment-history': typeof AppStudentsStudentIdEnrollmentHistoryRoute
  '/students/$studentId/finance': typeof AppStudentsStudentIdFinanceRoute
  '/students/$studentId/profile': typeof AppStudentsStudentIdProfileRoute
  '/students/$studentId/visa': typeof AppStudentsStudentIdVisaRoute
  '/academic/classes/': typeof AppAcademicClassesIndexRoute
  '/academic/levels/': typeof AppAcademicLevelsIndexRoute
  '/academic/programs/': typeof AppAcademicProgramsIndexRoute
  '/billing/fee-mappings/': typeof AppBillingFeeMappingsIndexRoute
  '/enrollment/academic-years/': typeof AppEnrollmentAcademicYearsIndexRoute
  '/enrollment/batches/': typeof AppEnrollmentBatchesIndexRoute
  '/enrollment/intake-batch/': typeof AppEnrollmentIntakeBatchIndexRoute
  '/enrollment/intakes/': typeof AppEnrollmentIntakesIndexRoute
  '/fees/categories/': typeof AppFeesCategoriesIndexRoute
  '/fees/discounts/': typeof AppFeesDiscountsIndexRoute
  '/users-access/permission-matrix/': typeof AppUsersAccessPermissionMatrixIndexRoute
  '/users-access/user-list/': typeof AppUsersAccessUserListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/platform': typeof PlatformRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/students/$studentId': typeof AppStudentsStudentIdRouteWithChildren
  '/students/new': typeof AppStudentsNewRoute
  '/academic': typeof AppAcademicIndexRoute
  '/audit': typeof AppAuditIndexRoute
  '/billing': typeof AppBillingIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/finance': typeof AppFinanceIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/users-access': typeof AppUsersAccessIndexRoute
  '/platform/dashboard': typeof PlatformDashboardIndexRoute
  '/students/$studentId/audit': typeof AppStudentsStudentIdAuditRoute
  '/students/$studentId/documents': typeof AppStudentsStudentIdDocumentsRoute
  '/students/$studentId/edit': typeof AppStudentsStudentIdEditRoute
  '/students/$studentId/enrollment-history': typeof AppStudentsStudentIdEnrollmentHistoryRoute
  '/students/$studentId/finance': typeof AppStudentsStudentIdFinanceRoute
  '/students/$studentId/profile': typeof AppStudentsStudentIdProfileRoute
  '/students/$studentId/visa': typeof AppStudentsStudentIdVisaRoute
  '/academic/classes': typeof AppAcademicClassesIndexRoute
  '/academic/levels': typeof AppAcademicLevelsIndexRoute
  '/academic/programs': typeof AppAcademicProgramsIndexRoute
  '/billing/fee-mappings': typeof AppBillingFeeMappingsIndexRoute
  '/enrollment/academic-years': typeof AppEnrollmentAcademicYearsIndexRoute
  '/enrollment/batches': typeof AppEnrollmentBatchesIndexRoute
  '/enrollment/intake-batch': typeof AppEnrollmentIntakeBatchIndexRoute
  '/enrollment/intakes': typeof AppEnrollmentIntakesIndexRoute
  '/fees/categories': typeof AppFeesCategoriesIndexRoute
  '/fees/discounts': typeof AppFeesDiscountsIndexRoute
  '/users-access/permission-matrix': typeof AppUsersAccessPermissionMatrixIndexRoute
  '/users-access/user-list': typeof AppUsersAccessUserListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_app/students/$studentId': typeof AppStudentsStudentIdRouteWithChildren
  '/_app/students/new': typeof AppStudentsNewRoute
  '/_app/academic/': typeof AppAcademicIndexRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/billing/': typeof AppBillingIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/finance/': typeof AppFinanceIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/_app/users-access/': typeof AppUsersAccessIndexRoute
  '/platform/dashboard/': typeof PlatformDashboardIndexRoute
  '/_app/students/$studentId/audit': typeof AppStudentsStudentIdAuditRoute
  '/_app/students/$studentId/documents': typeof AppStudentsStudentIdDocumentsRoute
  '/_app/students/$studentId/edit': typeof AppStudentsStudentIdEditRoute
  '/_app/students/$studentId/enrollment-history': typeof AppStudentsStudentIdEnrollmentHistoryRoute
  '/_app/students/$studentId/finance': typeof AppStudentsStudentIdFinanceRoute
  '/_app/students/$studentId/profile': typeof AppStudentsStudentIdProfileRoute
  '/_app/students/$studentId/visa': typeof AppStudentsStudentIdVisaRoute
  '/_app/academic/classes/': typeof AppAcademicClassesIndexRoute
  '/_app/academic/levels/': typeof AppAcademicLevelsIndexRoute
  '/_app/academic/programs/': typeof AppAcademicProgramsIndexRoute
  '/_app/billing/fee-mappings/': typeof AppBillingFeeMappingsIndexRoute
  '/_app/enrollment/academic-years/': typeof AppEnrollmentAcademicYearsIndexRoute
  '/_app/enrollment/batches/': typeof AppEnrollmentBatchesIndexRoute
  '/_app/enrollment/intake-batch/': typeof AppEnrollmentIntakeBatchIndexRoute
  '/_app/enrollment/intakes/': typeof AppEnrollmentIntakesIndexRoute
  '/_app/fees/categories/': typeof AppFeesCategoriesIndexRoute
  '/_app/fees/discounts/': typeof AppFeesDiscountsIndexRoute
  '/_app/users-access/permission-matrix/': typeof AppUsersAccessPermissionMatrixIndexRoute
  '/_app/users-access/user-list/': typeof AppUsersAccessUserListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/platform'
    | '/login'
    | '/students/$studentId'
    | '/students/new'
    | '/academic/'
    | '/audit/'
    | '/billing/'
    | '/dashboard/'
    | '/finance/'
    | '/settings/'
    | '/students/'
    | '/users-access/'
    | '/platform/dashboard/'
    | '/students/$studentId/audit'
    | '/students/$studentId/documents'
    | '/students/$studentId/edit'
    | '/students/$studentId/enrollment-history'
    | '/students/$studentId/finance'
    | '/students/$studentId/profile'
    | '/students/$studentId/visa'
    | '/academic/classes/'
    | '/academic/levels/'
    | '/academic/programs/'
    | '/billing/fee-mappings/'
    | '/enrollment/academic-years/'
    | '/enrollment/batches/'
    | '/enrollment/intake-batch/'
    | '/enrollment/intakes/'
    | '/fees/categories/'
    | '/fees/discounts/'
    | '/users-access/permission-matrix/'
    | '/users-access/user-list/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/platform'
    | '/login'
    | '/students/$studentId'
    | '/students/new'
    | '/academic'
    | '/audit'
    | '/billing'
    | '/dashboard'
    | '/finance'
    | '/settings'
    | '/students'
    | '/users-access'
    | '/platform/dashboard'
    | '/students/$studentId/audit'
    | '/students/$studentId/documents'
    | '/students/$studentId/edit'
    | '/students/$studentId/enrollment-history'
    | '/students/$studentId/finance'
    | '/students/$studentId/profile'
    | '/students/$studentId/visa'
    | '/academic/classes'
    | '/academic/levels'
    | '/academic/programs'
    | '/billing/fee-mappings'
    | '/enrollment/academic-years'
    | '/enrollment/batches'
    | '/enrollment/intake-batch'
    | '/enrollment/intakes'
    | '/fees/categories'
    | '/fees/discounts'
    | '/users-access/permission-matrix'
    | '/users-access/user-list'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/platform'
    | '/_auth/login'
    | '/_app/students/$studentId'
    | '/_app/students/new'
    | '/_app/academic/'
    | '/_app/audit/'
    | '/_app/billing/'
    | '/_app/dashboard/'
    | '/_app/finance/'
    | '/_app/settings/'
    | '/_app/students/'
    | '/_app/users-access/'
    | '/platform/dashboard/'
    | '/_app/students/$studentId/audit'
    | '/_app/students/$studentId/documents'
    | '/_app/students/$studentId/edit'
    | '/_app/students/$studentId/enrollment-history'
    | '/_app/students/$studentId/finance'
    | '/_app/students/$studentId/profile'
    | '/_app/students/$studentId/visa'
    | '/_app/academic/classes/'
    | '/_app/academic/levels/'
    | '/_app/academic/programs/'
    | '/_app/billing/fee-mappings/'
    | '/_app/enrollment/academic-years/'
    | '/_app/enrollment/batches/'
    | '/_app/enrollment/intake-batch/'
    | '/_app/enrollment/intakes/'
    | '/_app/fees/categories/'
    | '/_app/fees/discounts/'
    | '/_app/users-access/permission-matrix/'
    | '/_app/users-access/user-list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/platform/dashboard/': {
      id: '/platform/dashboard/'
      path: '/dashboard'
      fullPath: '/platform/dashboard/'
      preLoaderRoute: typeof PlatformDashboardIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_app/users-access/': {
      id: '/_app/users-access/'
      path: '/users-access'
      fullPath: '/users-access/'
      preLoaderRoute: typeof AppUsersAccessIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/': {
      id: '/_app/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing/': {
      id: '/_app/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/': {
      id: '/_app/academic/'
      path: '/academic'
      fullPath: '/academic/'
      preLoaderRoute: typeof AppAcademicIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/new': {
      id: '/_app/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AppStudentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$studentId': {
      id: '/_app/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users-access/user-list/': {
      id: '/_app/users-access/user-list/'
      path: '/users-access/user-list'
      fullPath: '/users-access/user-list/'
      preLoaderRoute: typeof AppUsersAccessUserListIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users-access/permission-matrix/': {
      id: '/_app/users-access/permission-matrix/'
      path: '/users-access/permission-matrix'
      fullPath: '/users-access/permission-matrix/'
      preLoaderRoute: typeof AppUsersAccessPermissionMatrixIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees/discounts/': {
      id: '/_app/fees/discounts/'
      path: '/fees/discounts'
      fullPath: '/fees/discounts/'
      preLoaderRoute: typeof AppFeesDiscountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees/categories/': {
      id: '/_app/fees/categories/'
      path: '/fees/categories'
      fullPath: '/fees/categories/'
      preLoaderRoute: typeof AppFeesCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/intakes/': {
      id: '/_app/enrollment/intakes/'
      path: '/enrollment/intakes'
      fullPath: '/enrollment/intakes/'
      preLoaderRoute: typeof AppEnrollmentIntakesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/intake-batch/': {
      id: '/_app/enrollment/intake-batch/'
      path: '/enrollment/intake-batch'
      fullPath: '/enrollment/intake-batch/'
      preLoaderRoute: typeof AppEnrollmentIntakeBatchIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/batches/': {
      id: '/_app/enrollment/batches/'
      path: '/enrollment/batches'
      fullPath: '/enrollment/batches/'
      preLoaderRoute: typeof AppEnrollmentBatchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/academic-years/': {
      id: '/_app/enrollment/academic-years/'
      path: '/enrollment/academic-years'
      fullPath: '/enrollment/academic-years/'
      preLoaderRoute: typeof AppEnrollmentAcademicYearsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing/fee-mappings/': {
      id: '/_app/billing/fee-mappings/'
      path: '/billing/fee-mappings'
      fullPath: '/billing/fee-mappings/'
      preLoaderRoute: typeof AppBillingFeeMappingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/programs/': {
      id: '/_app/academic/programs/'
      path: '/academic/programs'
      fullPath: '/academic/programs/'
      preLoaderRoute: typeof AppAcademicProgramsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/levels/': {
      id: '/_app/academic/levels/'
      path: '/academic/levels'
      fullPath: '/academic/levels/'
      preLoaderRoute: typeof AppAcademicLevelsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/classes/': {
      id: '/_app/academic/classes/'
      path: '/academic/classes'
      fullPath: '/academic/classes/'
      preLoaderRoute: typeof AppAcademicClassesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$studentId/visa': {
      id: '/_app/students/$studentId/visa'
      path: '/visa'
      fullPath: '/students/$studentId/visa'
      preLoaderRoute: typeof AppStudentsStudentIdVisaRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
    '/_app/students/$studentId/profile': {
      id: '/_app/students/$studentId/profile'
      path: '/profile'
      fullPath: '/students/$studentId/profile'
      preLoaderRoute: typeof AppStudentsStudentIdProfileRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
    '/_app/students/$studentId/finance': {
      id: '/_app/students/$studentId/finance'
      path: '/finance'
      fullPath: '/students/$studentId/finance'
      preLoaderRoute: typeof AppStudentsStudentIdFinanceRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
    '/_app/students/$studentId/enrollment-history': {
      id: '/_app/students/$studentId/enrollment-history'
      path: '/enrollment-history'
      fullPath: '/students/$studentId/enrollment-history'
      preLoaderRoute: typeof AppStudentsStudentIdEnrollmentHistoryRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
    '/_app/students/$studentId/edit': {
      id: '/_app/students/$studentId/edit'
      path: '/edit'
      fullPath: '/students/$studentId/edit'
      preLoaderRoute: typeof AppStudentsStudentIdEditRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
    '/_app/students/$studentId/documents': {
      id: '/_app/students/$studentId/documents'
      path: '/documents'
      fullPath: '/students/$studentId/documents'
      preLoaderRoute: typeof AppStudentsStudentIdDocumentsRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
    '/_app/students/$studentId/audit': {
      id: '/_app/students/$studentId/audit'
      path: '/audit'
      fullPath: '/students/$studentId/audit'
      preLoaderRoute: typeof AppStudentsStudentIdAuditRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
  }
}

interface AppStudentsStudentIdRouteChildren {
  AppStudentsStudentIdAuditRoute: typeof AppStudentsStudentIdAuditRoute
  AppStudentsStudentIdDocumentsRoute: typeof AppStudentsStudentIdDocumentsRoute
  AppStudentsStudentIdEditRoute: typeof AppStudentsStudentIdEditRoute
  AppStudentsStudentIdEnrollmentHistoryRoute: typeof AppStudentsStudentIdEnrollmentHistoryRoute
  AppStudentsStudentIdFinanceRoute: typeof AppStudentsStudentIdFinanceRoute
  AppStudentsStudentIdProfileRoute: typeof AppStudentsStudentIdProfileRoute
  AppStudentsStudentIdVisaRoute: typeof AppStudentsStudentIdVisaRoute
}

const AppStudentsStudentIdRouteChildren: AppStudentsStudentIdRouteChildren = {
  AppStudentsStudentIdAuditRoute: AppStudentsStudentIdAuditRoute,
  AppStudentsStudentIdDocumentsRoute: AppStudentsStudentIdDocumentsRoute,
  AppStudentsStudentIdEditRoute: AppStudentsStudentIdEditRoute,
  AppStudentsStudentIdEnrollmentHistoryRoute:
    AppStudentsStudentIdEnrollmentHistoryRoute,
  AppStudentsStudentIdFinanceRoute: AppStudentsStudentIdFinanceRoute,
  AppStudentsStudentIdProfileRoute: AppStudentsStudentIdProfileRoute,
  AppStudentsStudentIdVisaRoute: AppStudentsStudentIdVisaRoute,
}

const AppStudentsStudentIdRouteWithChildren =
  AppStudentsStudentIdRoute._addFileChildren(AppStudentsStudentIdRouteChildren)

interface AppRouteChildren {
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRouteWithChildren
  AppStudentsNewRoute: typeof AppStudentsNewRoute
  AppAcademicIndexRoute: typeof AppAcademicIndexRoute
  AppAuditIndexRoute: typeof AppAuditIndexRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppUsersAccessIndexRoute: typeof AppUsersAccessIndexRoute
  AppAcademicClassesIndexRoute: typeof AppAcademicClassesIndexRoute
  AppAcademicLevelsIndexRoute: typeof AppAcademicLevelsIndexRoute
  AppAcademicProgramsIndexRoute: typeof AppAcademicProgramsIndexRoute
  AppBillingFeeMappingsIndexRoute: typeof AppBillingFeeMappingsIndexRoute
  AppEnrollmentAcademicYearsIndexRoute: typeof AppEnrollmentAcademicYearsIndexRoute
  AppEnrollmentBatchesIndexRoute: typeof AppEnrollmentBatchesIndexRoute
  AppEnrollmentIntakeBatchIndexRoute: typeof AppEnrollmentIntakeBatchIndexRoute
  AppEnrollmentIntakesIndexRoute: typeof AppEnrollmentIntakesIndexRoute
  AppFeesCategoriesIndexRoute: typeof AppFeesCategoriesIndexRoute
  AppFeesDiscountsIndexRoute: typeof AppFeesDiscountsIndexRoute
  AppUsersAccessPermissionMatrixIndexRoute: typeof AppUsersAccessPermissionMatrixIndexRoute
  AppUsersAccessUserListIndexRoute: typeof AppUsersAccessUserListIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppStudentsStudentIdRoute: AppStudentsStudentIdRouteWithChildren,
  AppStudentsNewRoute: AppStudentsNewRoute,
  AppAcademicIndexRoute: AppAcademicIndexRoute,
  AppAuditIndexRoute: AppAuditIndexRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppFinanceIndexRoute: AppFinanceIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppUsersAccessIndexRoute: AppUsersAccessIndexRoute,
  AppAcademicClassesIndexRoute: AppAcademicClassesIndexRoute,
  AppAcademicLevelsIndexRoute: AppAcademicLevelsIndexRoute,
  AppAcademicProgramsIndexRoute: AppAcademicProgramsIndexRoute,
  AppBillingFeeMappingsIndexRoute: AppBillingFeeMappingsIndexRoute,
  AppEnrollmentAcademicYearsIndexRoute: AppEnrollmentAcademicYearsIndexRoute,
  AppEnrollmentBatchesIndexRoute: AppEnrollmentBatchesIndexRoute,
  AppEnrollmentIntakeBatchIndexRoute: AppEnrollmentIntakeBatchIndexRoute,
  AppEnrollmentIntakesIndexRoute: AppEnrollmentIntakesIndexRoute,
  AppFeesCategoriesIndexRoute: AppFeesCategoriesIndexRoute,
  AppFeesDiscountsIndexRoute: AppFeesDiscountsIndexRoute,
  AppUsersAccessPermissionMatrixIndexRoute:
    AppUsersAccessPermissionMatrixIndexRoute,
  AppUsersAccessUserListIndexRoute: AppUsersAccessUserListIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PlatformRouteChildren {
  PlatformDashboardIndexRoute: typeof PlatformDashboardIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformDashboardIndexRoute: PlatformDashboardIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
