/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PlatformDashboardIndexRouteImport } from './routes/platform/dashboard/index'
import { Route as AppStudentsIndexRouteImport } from './routes/_app/students/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppFinanceIndexRouteImport } from './routes/_app/finance/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppBillingIndexRouteImport } from './routes/_app/billing/index'
import { Route as AppAuditIndexRouteImport } from './routes/_app/audit/index'
import { Route as AppAdministrationIndexRouteImport } from './routes/_app/administration/index'
import { Route as AppAcademicIndexRouteImport } from './routes/_app/academic/index'
import { Route as AppStudentsNewRouteImport } from './routes/_app/students/new'
import { Route as AppStudentsStudentIdRouteImport } from './routes/_app/students/$studentId'
import { Route as AppEnrollmentIntakesIndexRouteImport } from './routes/_app/enrollment/intakes/index'
import { Route as AppEnrollmentIntakeBatchIndexRouteImport } from './routes/_app/enrollment/intake-batch/index'
import { Route as AppEnrollmentBatchesIndexRouteImport } from './routes/_app/enrollment/batches/index'
import { Route as AppEnrollmentAcademicYearsIndexRouteImport } from './routes/_app/enrollment/academic-years/index'
import { Route as AppStudentsStudentIdVisaRouteImport } from './routes/_app/students/$studentId/visa'
import { Route as AppStudentsStudentIdOverviewRouteImport } from './routes/_app/students/$studentId/overview'
import { Route as AppStudentsStudentIdFinanceRouteImport } from './routes/_app/students/$studentId/finance'
import { Route as AppStudentsStudentIdDocumentsRouteImport } from './routes/_app/students/$studentId/documents'
import { Route as AppStudentsStudentIdActivityRouteImport } from './routes/_app/students/$studentId/activity'
import { Route as AppStudentsStudentIdAcademicRouteImport } from './routes/_app/students/$studentId/academic'

const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const PlatformDashboardIndexRoute = PlatformDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => PlatformRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministrationIndexRoute = AppAdministrationIndexRouteImport.update({
  id: '/administration/',
  path: '/administration/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicIndexRoute = AppAcademicIndexRouteImport.update({
  id: '/academic/',
  path: '/academic/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsNewRoute = AppStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AppRoute,
} as any)
const AppEnrollmentIntakesIndexRoute =
  AppEnrollmentIntakesIndexRouteImport.update({
    id: '/enrollment/intakes/',
    path: '/enrollment/intakes/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEnrollmentIntakeBatchIndexRoute =
  AppEnrollmentIntakeBatchIndexRouteImport.update({
    id: '/enrollment/intake-batch/',
    path: '/enrollment/intake-batch/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEnrollmentBatchesIndexRoute =
  AppEnrollmentBatchesIndexRouteImport.update({
    id: '/enrollment/batches/',
    path: '/enrollment/batches/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEnrollmentAcademicYearsIndexRoute =
  AppEnrollmentAcademicYearsIndexRouteImport.update({
    id: '/enrollment/academic-years/',
    path: '/enrollment/academic-years/',
    getParentRoute: () => AppRoute,
  } as any)
const AppStudentsStudentIdVisaRoute =
  AppStudentsStudentIdVisaRouteImport.update({
    id: '/visa',
    path: '/visa',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)
const AppStudentsStudentIdOverviewRoute =
  AppStudentsStudentIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)
const AppStudentsStudentIdFinanceRoute =
  AppStudentsStudentIdFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)
const AppStudentsStudentIdDocumentsRoute =
  AppStudentsStudentIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)
const AppStudentsStudentIdActivityRoute =
  AppStudentsStudentIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)
const AppStudentsStudentIdAcademicRoute =
  AppStudentsStudentIdAcademicRouteImport.update({
    id: '/academic',
    path: '/academic',
    getParentRoute: () => AppStudentsStudentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platform': typeof PlatformRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/students/$studentId': typeof AppStudentsStudentIdRouteWithChildren
  '/students/new': typeof AppStudentsNewRoute
  '/academic/': typeof AppAcademicIndexRoute
  '/administration/': typeof AppAdministrationIndexRoute
  '/audit/': typeof AppAuditIndexRoute
  '/billing/': typeof AppBillingIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/finance/': typeof AppFinanceIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/students/': typeof AppStudentsIndexRoute
  '/platform/dashboard/': typeof PlatformDashboardIndexRoute
  '/students/$studentId/academic': typeof AppStudentsStudentIdAcademicRoute
  '/students/$studentId/activity': typeof AppStudentsStudentIdActivityRoute
  '/students/$studentId/documents': typeof AppStudentsStudentIdDocumentsRoute
  '/students/$studentId/finance': typeof AppStudentsStudentIdFinanceRoute
  '/students/$studentId/overview': typeof AppStudentsStudentIdOverviewRoute
  '/students/$studentId/visa': typeof AppStudentsStudentIdVisaRoute
  '/enrollment/academic-years/': typeof AppEnrollmentAcademicYearsIndexRoute
  '/enrollment/batches/': typeof AppEnrollmentBatchesIndexRoute
  '/enrollment/intake-batch/': typeof AppEnrollmentIntakeBatchIndexRoute
  '/enrollment/intakes/': typeof AppEnrollmentIntakesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/platform': typeof PlatformRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/students/$studentId': typeof AppStudentsStudentIdRouteWithChildren
  '/students/new': typeof AppStudentsNewRoute
  '/academic': typeof AppAcademicIndexRoute
  '/administration': typeof AppAdministrationIndexRoute
  '/audit': typeof AppAuditIndexRoute
  '/billing': typeof AppBillingIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/finance': typeof AppFinanceIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/students': typeof AppStudentsIndexRoute
  '/platform/dashboard': typeof PlatformDashboardIndexRoute
  '/students/$studentId/academic': typeof AppStudentsStudentIdAcademicRoute
  '/students/$studentId/activity': typeof AppStudentsStudentIdActivityRoute
  '/students/$studentId/documents': typeof AppStudentsStudentIdDocumentsRoute
  '/students/$studentId/finance': typeof AppStudentsStudentIdFinanceRoute
  '/students/$studentId/overview': typeof AppStudentsStudentIdOverviewRoute
  '/students/$studentId/visa': typeof AppStudentsStudentIdVisaRoute
  '/enrollment/academic-years': typeof AppEnrollmentAcademicYearsIndexRoute
  '/enrollment/batches': typeof AppEnrollmentBatchesIndexRoute
  '/enrollment/intake-batch': typeof AppEnrollmentIntakeBatchIndexRoute
  '/enrollment/intakes': typeof AppEnrollmentIntakesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_app/students/$studentId': typeof AppStudentsStudentIdRouteWithChildren
  '/_app/students/new': typeof AppStudentsNewRoute
  '/_app/academic/': typeof AppAcademicIndexRoute
  '/_app/administration/': typeof AppAdministrationIndexRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/billing/': typeof AppBillingIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/finance/': typeof AppFinanceIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/students/': typeof AppStudentsIndexRoute
  '/platform/dashboard/': typeof PlatformDashboardIndexRoute
  '/_app/students/$studentId/academic': typeof AppStudentsStudentIdAcademicRoute
  '/_app/students/$studentId/activity': typeof AppStudentsStudentIdActivityRoute
  '/_app/students/$studentId/documents': typeof AppStudentsStudentIdDocumentsRoute
  '/_app/students/$studentId/finance': typeof AppStudentsStudentIdFinanceRoute
  '/_app/students/$studentId/overview': typeof AppStudentsStudentIdOverviewRoute
  '/_app/students/$studentId/visa': typeof AppStudentsStudentIdVisaRoute
  '/_app/enrollment/academic-years/': typeof AppEnrollmentAcademicYearsIndexRoute
  '/_app/enrollment/batches/': typeof AppEnrollmentBatchesIndexRoute
  '/_app/enrollment/intake-batch/': typeof AppEnrollmentIntakeBatchIndexRoute
  '/_app/enrollment/intakes/': typeof AppEnrollmentIntakesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/platform'
    | '/login'
    | '/students/$studentId'
    | '/students/new'
    | '/academic/'
    | '/administration/'
    | '/audit/'
    | '/billing/'
    | '/dashboard/'
    | '/finance/'
    | '/settings/'
    | '/students/'
    | '/platform/dashboard/'
    | '/students/$studentId/academic'
    | '/students/$studentId/activity'
    | '/students/$studentId/documents'
    | '/students/$studentId/finance'
    | '/students/$studentId/overview'
    | '/students/$studentId/visa'
    | '/enrollment/academic-years/'
    | '/enrollment/batches/'
    | '/enrollment/intake-batch/'
    | '/enrollment/intakes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/platform'
    | '/login'
    | '/students/$studentId'
    | '/students/new'
    | '/academic'
    | '/administration'
    | '/audit'
    | '/billing'
    | '/dashboard'
    | '/finance'
    | '/settings'
    | '/students'
    | '/platform/dashboard'
    | '/students/$studentId/academic'
    | '/students/$studentId/activity'
    | '/students/$studentId/documents'
    | '/students/$studentId/finance'
    | '/students/$studentId/overview'
    | '/students/$studentId/visa'
    | '/enrollment/academic-years'
    | '/enrollment/batches'
    | '/enrollment/intake-batch'
    | '/enrollment/intakes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/platform'
    | '/_auth/login'
    | '/_app/students/$studentId'
    | '/_app/students/new'
    | '/_app/academic/'
    | '/_app/administration/'
    | '/_app/audit/'
    | '/_app/billing/'
    | '/_app/dashboard/'
    | '/_app/finance/'
    | '/_app/settings/'
    | '/_app/students/'
    | '/platform/dashboard/'
    | '/_app/students/$studentId/academic'
    | '/_app/students/$studentId/activity'
    | '/_app/students/$studentId/documents'
    | '/_app/students/$studentId/finance'
    | '/_app/students/$studentId/overview'
    | '/_app/students/$studentId/visa'
    | '/_app/enrollment/academic-years/'
    | '/_app/enrollment/batches/'
    | '/_app/enrollment/intake-batch/'
    | '/_app/enrollment/intakes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/platform/dashboard/': {
      id: '/platform/dashboard/'
      path: '/dashboard'
      fullPath: '/platform/dashboard/'
      preLoaderRoute: typeof PlatformDashboardIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_app/students/': {
      id: '/_app/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/': {
      id: '/_app/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing/': {
      id: '/_app/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/': {
      id: '/_app/administration/'
      path: '/administration'
      fullPath: '/administration/'
      preLoaderRoute: typeof AppAdministrationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic/': {
      id: '/_app/academic/'
      path: '/academic'
      fullPath: '/academic/'
      preLoaderRoute: typeof AppAcademicIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/new': {
      id: '/_app/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AppStudentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$studentId': {
      id: '/_app/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/intakes/': {
      id: '/_app/enrollment/intakes/'
      path: '/enrollment/intakes'
      fullPath: '/enrollment/intakes/'
      preLoaderRoute: typeof AppEnrollmentIntakesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/intake-batch/': {
      id: '/_app/enrollment/intake-batch/'
      path: '/enrollment/intake-batch'
      fullPath: '/enrollment/intake-batch/'
      preLoaderRoute: typeof AppEnrollmentIntakeBatchIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/batches/': {
      id: '/_app/enrollment/batches/'
      path: '/enrollment/batches'
      fullPath: '/enrollment/batches/'
      preLoaderRoute: typeof AppEnrollmentBatchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/academic-years/': {
      id: '/_app/enrollment/academic-years/'
      path: '/enrollment/academic-years'
      fullPath: '/enrollment/academic-years/'
      preLoaderRoute: typeof AppEnrollmentAcademicYearsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$studentId/visa': {
      id: '/_app/students/$studentId/visa'
      path: '/visa'
      fullPath: '/students/$studentId/visa'
      preLoaderRoute: typeof AppStudentsStudentIdVisaRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
    '/_app/students/$studentId/overview': {
      id: '/_app/students/$studentId/overview'
      path: '/overview'
      fullPath: '/students/$studentId/overview'
      preLoaderRoute: typeof AppStudentsStudentIdOverviewRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
    '/_app/students/$studentId/finance': {
      id: '/_app/students/$studentId/finance'
      path: '/finance'
      fullPath: '/students/$studentId/finance'
      preLoaderRoute: typeof AppStudentsStudentIdFinanceRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
    '/_app/students/$studentId/documents': {
      id: '/_app/students/$studentId/documents'
      path: '/documents'
      fullPath: '/students/$studentId/documents'
      preLoaderRoute: typeof AppStudentsStudentIdDocumentsRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
    '/_app/students/$studentId/activity': {
      id: '/_app/students/$studentId/activity'
      path: '/activity'
      fullPath: '/students/$studentId/activity'
      preLoaderRoute: typeof AppStudentsStudentIdActivityRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
    '/_app/students/$studentId/academic': {
      id: '/_app/students/$studentId/academic'
      path: '/academic'
      fullPath: '/students/$studentId/academic'
      preLoaderRoute: typeof AppStudentsStudentIdAcademicRouteImport
      parentRoute: typeof AppStudentsStudentIdRoute
    }
  }
}

interface AppStudentsStudentIdRouteChildren {
  AppStudentsStudentIdAcademicRoute: typeof AppStudentsStudentIdAcademicRoute
  AppStudentsStudentIdActivityRoute: typeof AppStudentsStudentIdActivityRoute
  AppStudentsStudentIdDocumentsRoute: typeof AppStudentsStudentIdDocumentsRoute
  AppStudentsStudentIdFinanceRoute: typeof AppStudentsStudentIdFinanceRoute
  AppStudentsStudentIdOverviewRoute: typeof AppStudentsStudentIdOverviewRoute
  AppStudentsStudentIdVisaRoute: typeof AppStudentsStudentIdVisaRoute
}

const AppStudentsStudentIdRouteChildren: AppStudentsStudentIdRouteChildren = {
  AppStudentsStudentIdAcademicRoute: AppStudentsStudentIdAcademicRoute,
  AppStudentsStudentIdActivityRoute: AppStudentsStudentIdActivityRoute,
  AppStudentsStudentIdDocumentsRoute: AppStudentsStudentIdDocumentsRoute,
  AppStudentsStudentIdFinanceRoute: AppStudentsStudentIdFinanceRoute,
  AppStudentsStudentIdOverviewRoute: AppStudentsStudentIdOverviewRoute,
  AppStudentsStudentIdVisaRoute: AppStudentsStudentIdVisaRoute,
}

const AppStudentsStudentIdRouteWithChildren =
  AppStudentsStudentIdRoute._addFileChildren(AppStudentsStudentIdRouteChildren)

interface AppRouteChildren {
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRouteWithChildren
  AppStudentsNewRoute: typeof AppStudentsNewRoute
  AppAcademicIndexRoute: typeof AppAcademicIndexRoute
  AppAdministrationIndexRoute: typeof AppAdministrationIndexRoute
  AppAuditIndexRoute: typeof AppAuditIndexRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppEnrollmentAcademicYearsIndexRoute: typeof AppEnrollmentAcademicYearsIndexRoute
  AppEnrollmentBatchesIndexRoute: typeof AppEnrollmentBatchesIndexRoute
  AppEnrollmentIntakeBatchIndexRoute: typeof AppEnrollmentIntakeBatchIndexRoute
  AppEnrollmentIntakesIndexRoute: typeof AppEnrollmentIntakesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppStudentsStudentIdRoute: AppStudentsStudentIdRouteWithChildren,
  AppStudentsNewRoute: AppStudentsNewRoute,
  AppAcademicIndexRoute: AppAcademicIndexRoute,
  AppAdministrationIndexRoute: AppAdministrationIndexRoute,
  AppAuditIndexRoute: AppAuditIndexRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppFinanceIndexRoute: AppFinanceIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppEnrollmentAcademicYearsIndexRoute: AppEnrollmentAcademicYearsIndexRoute,
  AppEnrollmentBatchesIndexRoute: AppEnrollmentBatchesIndexRoute,
  AppEnrollmentIntakeBatchIndexRoute: AppEnrollmentIntakeBatchIndexRoute,
  AppEnrollmentIntakesIndexRoute: AppEnrollmentIntakesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PlatformRouteChildren {
  PlatformDashboardIndexRoute: typeof PlatformDashboardIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformDashboardIndexRoute: PlatformDashboardIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
